# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .task_status import TaskStatus


class UpdateTaskRequest(UniversalBaseModel):
    title: str
    description: typing.Optional[str] = None
    status: typing.Optional[TaskStatus] = None
    priority: typing.Optional[int] = None
    duration_seconds: typing.Optional[int] = None
    deadline: typing.Optional[dt.datetime] = None
    prerequisite_tasks: typing.Optional[typing.List[uuid.UUID]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
