# This file was auto-generated by Fern from our API Definition.

import abc
import functools
import inspect
import logging
import typing

import fastapi
from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args
from ..types.create_task_request import CreateTaskRequest
from ..types.task import Task
from ..types.update_task_request import UpdateTaskRequest


class AbstractTasksService(AbstractFernService):
    """
    AbstractTasksService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def create_task(self, *, body: CreateTaskRequest) -> Task: ...

    @abc.abstractmethod
    def update_task(self, *, body: UpdateTaskRequest) -> Task: ...

    @abc.abstractmethod
    def delete_task(self) -> Task: ...

    @abc.abstractmethod
    def get_tasks(self) -> typing.Sequence[Task]: ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_create_task(router=router)
        cls.__init_update_task(router=router)
        cls.__init_delete_task(router=router)
        cls.__init_get_tasks(router=router)

    @classmethod
    def __init_create_task(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.create_task)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.create_task, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.create_task)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Task:
            try:
                return cls.create_task(*args, **kwargs)
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'create_task' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.create_task.__globals__)

        router.post(
            path="/api/create-task",
            response_model=Task,
            description=AbstractTasksService.create_task.__doc__,
            **get_route_args(cls.create_task, default_tag="tasks"),
        )(wrapper)

    @classmethod
    def __init_update_task(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.update_task)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.update_task, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.update_task)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Task:
            try:
                return cls.update_task(*args, **kwargs)
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'update_task' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.update_task.__globals__)

        router.put(
            path="/api/update-task",
            response_model=Task,
            description=AbstractTasksService.update_task.__doc__,
            **get_route_args(cls.update_task, default_tag="tasks"),
        )(wrapper)

    @classmethod
    def __init_delete_task(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.delete_task)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            else:
                new_parameters.append(parameter)
        setattr(cls.delete_task, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.delete_task)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Task:
            try:
                return cls.delete_task(*args, **kwargs)
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'delete_task' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.delete_task.__globals__)

        router.delete(
            path="/api/delete-task",
            response_model=Task,
            description=AbstractTasksService.delete_task.__doc__,
            **get_route_args(cls.delete_task, default_tag="tasks"),
        )(wrapper)

    @classmethod
    def __init_get_tasks(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_tasks)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            else:
                new_parameters.append(parameter)
        setattr(cls.get_tasks, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_tasks)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> typing.Sequence[Task]:
            try:
                return cls.get_tasks(*args, **kwargs)
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_tasks' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_tasks.__globals__)

        router.get(
            path="/api/get-tasks",
            response_model=typing.Sequence[Task],
            description=AbstractTasksService.get_tasks.__doc__,
            **get_route_args(cls.get_tasks, default_tag="tasks"),
        )(wrapper)
