/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const TaskmasterTaskmasterEnvironment = {
    Local: "http://127.0.0.1:8000",
} as const;

export type TaskmasterTaskmasterEnvironment = typeof TaskmasterTaskmasterEnvironment.Local;
