/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TaskmasterTaskmaster from "../../../index.js";

export interface GenerateTasksRequest {
    transcript: string;
    existing_tasks?: TaskmasterTaskmaster.Task[];
}
