/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TaskmasterTaskmaster from "../../../index.js";

export interface GenerateTasksResponse {
    tasks: TaskmasterTaskmaster.Task[];
}
