/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TaskStatus = "TODO" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
export const TaskStatus = {
    Todo: "TODO",
    InProgress: "IN_PROGRESS",
    Completed: "COMPLETED",
    Cancelled: "CANCELLED",
} as const;
