/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TaskmasterTaskmaster from "../../../index.js";

export interface Task {
    id: string;
    title: string;
    description: string;
    status: TaskmasterTaskmaster.TaskStatus;
    priority: number;
    duration_seconds: number;
    prerequisite_tasks: string[];
    deadline?: string;
}
