/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TaskmasterTaskmaster from "../../../index.js";

export interface UpdateTaskRequest {
    title: string;
    description?: string;
    status?: TaskmasterTaskmaster.TaskStatus;
    priority?: number;
    duration_seconds?: number;
    deadline?: string;
    prerequisite_tasks?: string[];
}
